[[TracyProfiler]]
arch = "aarch64"
git-tree-sha1 = "29589b5d11821a04dc02cbf1c7adb82998ab7160"
os = "macos"

    [[TracyProfiler.download]]
    sha256 = "0bf5e9531265e46da9644c6e48b2f61debd35021d6dd665772a706a56d8bb045"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+0/TracyProfiler.v0.13.1.aarch64-apple-darwin.tar.gz"
[[TracyProfiler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd28c09149520968d3278a53329000e4b707351b"
libc = "glibc"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "d6eec4b34bd7108f2baf20e1fc3fc5a92f16323b13c7805e8c61405d41668744"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+0/TracyProfiler.v0.13.1.aarch64-linux-gnu-cxx11.tar.gz"
[[TracyProfiler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc434cdfca6f7aaedfe9eeb6034bfffe0a95253a"
libc = "musl"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "d0835e057d8774a0a77b0482c40a286dc74e195a881e74259494879f64f2b4fc"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+0/TracyProfiler.v0.13.1.aarch64-linux-musl-cxx11.tar.gz"
[[TracyProfiler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e089351fcea2389f89f637ce6bb813afd4d30dd0"
libc = "glibc"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "f8d70f58b7cebbf89d0a7eb94fe49fd925aec1531f66c93c6b2538a02655ad90"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+0/TracyProfiler.v0.13.1.i686-linux-gnu-cxx11.tar.gz"
[[TracyProfiler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7eb4d5feaba85d13503c5efa38795286fbe69e1a"
libc = "musl"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "3ae5bdacbce5aec928da6ea93acd18c84d9e765dd8b016979eba1d9452108690"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+0/TracyProfiler.v0.13.1.i686-linux-musl-cxx11.tar.gz"
[[TracyProfiler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0bfb1d8611311c13b37e7f3e45cf55ad3f3b7ea6"
os = "windows"

    [[TracyProfiler.download]]
    sha256 = "ea6c94e8b53d4d6fe2cdb22163055670d26fefd473094db055b26663ce383075"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+0/TracyProfiler.v0.13.1.i686-w64-mingw32-cxx11.tar.gz"
[[TracyProfiler]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4978693f6e359def71466155c64042bce85240c5"
libc = "glibc"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "003a9072fc05be82c562a62433ddc4b35818d9b7ff7bfe03b3ee28e2aaff03fc"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+0/TracyProfiler.v0.13.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[TracyProfiler]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85bfabec58093e3d70580e4193f9fe59069bbe67"
libc = "glibc"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "ce51b198f1b2c2be608053930242678e50ee610547e23b979e522381d9c6307e"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+0/TracyProfiler.v0.13.1.riscv64-linux-gnu-cxx11.tar.gz"
[[TracyProfiler]]
arch = "x86_64"
git-tree-sha1 = "1ae82fcd0e37278e74b5fe4d606b314388579723"
os = "macos"

    [[TracyProfiler.download]]
    sha256 = "8ee29500ea6c38c2ffb705fed668167bc733c1a7406525d24128b38e36cc0a6a"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+0/TracyProfiler.v0.13.1.x86_64-apple-darwin.tar.gz"
[[TracyProfiler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95254d6186564ae17d97302e8c8e0bfca09d774d"
libc = "glibc"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "eb50543ef59b273c7f77de42ea6a5e8f1ce16aea356c3f41b8c0b1bc2b90b86b"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+0/TracyProfiler.v0.13.1.x86_64-linux-gnu-cxx11.tar.gz"
[[TracyProfiler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e42c8b1dc8456a5a2013ecfa3cc4357a44f13296"
libc = "musl"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "467a8008bc7274e09d952d53969f7291e52291bdf37e8d9d5e492848001231b3"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+0/TracyProfiler.v0.13.1.x86_64-linux-musl-cxx11.tar.gz"
[[TracyProfiler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7dee5706fad67e585b9a24fecf9d197b30e39ea"
os = "windows"

    [[TracyProfiler.download]]
    sha256 = "77b35c7e66d44b5ddd60009b02ffb93337a8e827cc9ed30036203c0c179eb7b6"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+0/TracyProfiler.v0.13.1.x86_64-w64-mingw32-cxx11.tar.gz"
