[[TracyProfiler]]
arch = "aarch64"
git-tree-sha1 = "9ec6af8950ad4016c34d0a9e3636dfea111b7a39"
os = "macos"

    [[TracyProfiler.download]]
    sha256 = "d2b8a34b335dcfe29534d1796651046d67b5fee9fba35b274c8e97da62433785"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+1/TracyProfiler.v0.13.1.aarch64-apple-darwin.tar.gz"
[[TracyProfiler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1b0c939cfa9d5faa391a2a0db145845aff67abdb"
libc = "glibc"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "b4d12ab97b58ed907605bd51df2fcf729e3d6fe2603b20ea4dfdd68885317110"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+1/TracyProfiler.v0.13.1.aarch64-linux-gnu-cxx11.tar.gz"
[[TracyProfiler]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f6adb7f7a1abdc65252f64c4b040ad910fbe979"
libc = "musl"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "a19b246016e3fcbaaaa67e929d52698bf55f267ec955779fdaf1ad75b77b2395"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+1/TracyProfiler.v0.13.1.aarch64-linux-musl-cxx11.tar.gz"
[[TracyProfiler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c1daf872ebb4e763bca6763ff4601badc0ff651"
libc = "glibc"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "930bba4772f89cf95dec397da9b86330f141b09644a2ef316e6a9cad0c1f5579"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+1/TracyProfiler.v0.13.1.i686-linux-gnu-cxx11.tar.gz"
[[TracyProfiler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d327736824570c59d953ccefe77026a0eb903ca4"
libc = "musl"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "c0f78e527efdff2bc924eb39d1b2596aaae3bc956487ee7cb42ca1f9049ae8e0"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+1/TracyProfiler.v0.13.1.i686-linux-musl-cxx11.tar.gz"
[[TracyProfiler]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fece59a229b9595083702915213258d4e2d979fb"
os = "windows"

    [[TracyProfiler.download]]
    sha256 = "42bb05521068a4b1a2703a53cae7d4b6386df494aa3ee626ae57308dd6f545c9"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+1/TracyProfiler.v0.13.1.i686-w64-mingw32-cxx11.tar.gz"
[[TracyProfiler]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2654b6459082611cf3011138f629bc328a9f85fe"
libc = "glibc"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "2cbe95f839af79fe87ebf337aa10f2a1121d4753569c616568940fbb0a709114"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+1/TracyProfiler.v0.13.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[TracyProfiler]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3735755d3380a0ac5d2f4c9dc8d4fbc477596a7f"
libc = "glibc"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "547cfe6779f3c603ca500a79783d64c483d290149709c49448f8de6574d549e8"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+1/TracyProfiler.v0.13.1.riscv64-linux-gnu-cxx11.tar.gz"
[[TracyProfiler]]
arch = "x86_64"
git-tree-sha1 = "d1ed102f1027cbdc775bee314ca2f8152d36e740"
os = "macos"

    [[TracyProfiler.download]]
    sha256 = "4f18d627468c013976d568c6a3184adfefbe9ffe6cbdd635a4f4a1b5d63a36e2"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+1/TracyProfiler.v0.13.1.x86_64-apple-darwin.tar.gz"
[[TracyProfiler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ee083d26d594ca7cffd612cabcd6810995599e3"
libc = "glibc"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "bcb20b2a146383cb4ecaf9fda02373db307d8b0d7c929665b7367f671c193623"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+1/TracyProfiler.v0.13.1.x86_64-linux-gnu-cxx11.tar.gz"
[[TracyProfiler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e0a921c4a657cb6dee0a7f12152540dc249f9c0"
libc = "musl"
os = "linux"

    [[TracyProfiler.download]]
    sha256 = "1e29e3062f604b55af652408d4d4fdffec92edf4603f62333b21f25b432f40cc"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+1/TracyProfiler.v0.13.1.x86_64-linux-musl-cxx11.tar.gz"
[[TracyProfiler]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6da44d2d5aafd5cc1028c202ebe2f781c153e2f5"
os = "windows"

    [[TracyProfiler.download]]
    sha256 = "4bc44be03b52e8373f86d2389eea53f016f787c01933d717984ccb01768a04c2"
    url = "https://github.com/JuliaBinaryWrappers/TracyProfiler_jll.jl/releases/download/TracyProfiler-v0.13.1+1/TracyProfiler.v0.13.1.x86_64-w64-mingw32-cxx11.tar.gz"
