name = "TracyProfiler_jll"
uuid = "0c351ed6-8a68-550e-8b79-de6f926da83c"
version = "0.13.1+0"

[deps]
Xorg_libXcursor_jll = "935fb764-8cf2-53bf-bb30-45bb1f8bf724"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
FreeType2_jll = "d7e528f0-a631-5988-bf34-fe36492bcfd7"
GLFW_jll = "0656b61e-2033-5cc2-a64a-77c0f6c09b89"
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Xorg_libX11_jll = "4f6342f7-b3d2-589e-9d20-edeb45f2b2bc"
Xorg_libXrandr_jll = "ec84b674-ba8e-5d96-8ba1-2a689ba10484"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
LibCURL_jll = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"
Xorg_libXinerama_jll = "d1454406-59df-5ea1-beac-c340f2130bc3"
Dbus_jll = "ee1fde0b-3d02-5ea6-8484-8dfef6360eab"
Xorg_libXi_jll = "a51aa0fd-4e3c-5386-b890-e753decda492"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
LibCURL_jll = "7.88.1,8"
FreeType2_jll = "2.10.4"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
